# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-11 12:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0005_auto_20181210_2223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='post_code',
            new_name='postal_code',
        ),
    ]
